apiVersion: v1
kind: Service
metadata:
  name: api-service
  # Add namespace if needed, e.g.:
  # namespace: your-namespace

spec:
  # ClusterIP is the default type, but explicitly stating it is fine
  type: ClusterIP
  selector:
    app: synergychat-api # This must match the 'app' label on your pods
  ports:
    - protocol: TCP
      port: 80 # The port the service exposes
      targetPort: 8080 # The port your application container is listening on
      # Removed: nodePort: 30080 (not valid for ClusterIP)

